title: The Epping Forest Pipe Band
author: The Epping Forest Pipe Band
email: secretary@efpb.org
description: >-
  Epping Forest Pipe Band shares the stirring sounds of Scotland, performing since 1974. Join us in celebrating music, tradition, and community.

social:
  twitter: EFPB_UK
  facebook: EppingForestPipeBand
  instagram: epping_forest_pipe_band_
  github: EppingForestPipeBand

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
