backend:
  name: github
  repo: your-github-username/your-repo-name
  branch: main
  auth_scope: repo
  auth_endpoint: https://github.com/login/oauth/authorize
  base_url: https://your-site.com
  auth_type: implicit
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"
collections:
  # Pages collection for main site pages
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Order", name: "order", widget: "number", required: false}

  # Home page as a file collection
  - name: "home"
    label: "Home"
    files:
      - name: "home"
        label: "Home Page"
        file: "_pages/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Text", name: "hero_text", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
