# Analyzes GitHub workflow files for security and best practices using zizmor

name: analyse_workflows

on:
  push:
    paths:
      - '.github/**'
  schedule:
    - cron: "1 0 1 * *"
    
permissions:
  contents: write

jobs:
  zizmor:
    name: zizmor latest via Cargo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4

      - name: Run zizmor 🌈
        run: uvx zizmor --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3.27.9
        with:
          sarif_file: results.sarif
          category: zizmor
