name: Check Image-Markdown Correspondence

on:
  push:
    paths:
      - '_images/**'
      - 'assets/images/fulls/**'
  pull_request:
    paths:
      - '_images/**'
      - 'assets/images/fulls/**'
  workflow_dispatch:

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check file correspondence
        run: |
          # Check if each markdown file has a corresponding image
          for md_file in _images/*.md; do
            base_name=$(basename "$md_file" .md)
            if [ ! -f "assets/images/fulls/$base_name.jpg" ]; then
              echo "Error: Missing image for $md_file"
              echo "Expected: assets/images/fulls/$base_name.jpg"
              echo "Please ensure that all _images/*.md files have corresponding images in assets/images/fulls/"
              exit 1
            fi
          done

          # Check if each image has a corresponding markdown file
          for img_file in assets/images/fulls/*.jpg; do
            base_name=$(basename "$img_file" .jpg)
            if [ ! -f "_images/$base_name.md" ]; then
              echo "Error: Missing markdown file for $img_file"
              echo "Expected: _images/$base_name.md"
              echo "Please ensure that all images in assets/images/fulls/ have corresponding markdown files in _images/"
              exit 1
            fi
          done

          echo "✅ All files have corresponding pairs" 