name: Generate Image Thumbnails

on:
  push:
    paths:
      - 'assets/images/fulls/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  thumbnails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install FUSE and ImageMagick 7
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse
          wget -q https://imagemagick.org/archive/binaries/magick
          chmod +x magick
          sudo mv magick /usr/local/bin/
          magick -version

      - name: Create thumbs directory if not exists
        run: mkdir -p assets/images/thumbs

      - name: Generate thumbnails
        run: |
          for img in assets/images/fulls/*.jpg; do
            filename=$(basename "$img")
              magick "$img" -resize "360x" "assets/images/thumbs/$filename"
          done

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/images/thumbs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generate thumbnails" && git push)
